# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bisystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceno', models.CharField(blank=True, db_column='InvoiceNo', max_length=255, null=True)),
                ('invoicedate', models.CharField(blank=True, db_column='InvoiceDate', max_length=255, null=True)),
                ('customerid', models.CharField(blank=True, db_column='CustomerID', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True)),
                ('quantity', models.CharField(blank=True, db_column='Quantity', max_length=255, null=True)),
                ('unitprice', models.CharField(blank=True, db_column='UnitPrice', max_length=255, null=True)),
                ('broughtprice', models.CharField(blank=True, db_column='BroughtPrice', max_length=255, null=True)),
                ('profit', models.CharField(blank=True, db_column='Profit', max_length=255, null=True)),
                ('loggedos', models.CharField(blank=True, db_column='LoggedOS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Bisystem',
                'managed': False,
            },
        ),
    ]
